// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hichain/hichain/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreatePost struct {
	Creator                string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SYSTakipNo             string `protobuf:"bytes,2,opt,name=sYSTakipNo,proto3" json:"sYSTakipNo,omitempty"`
	AD                     string `protobuf:"bytes,3,opt,name=aD,proto3" json:"aD,omitempty"`
	SOYAD                  string `protobuf:"bytes,4,opt,name=sOYAD,proto3" json:"sOYAD,omitempty"`
	DOGUMTARIHI            string `protobuf:"bytes,5,opt,name=dOGUMTARIHI,proto3" json:"dOGUMTARIHI,omitempty"`
	CINSIYET               string `protobuf:"bytes,6,opt,name=cINSIYET,proto3" json:"cINSIYET,omitempty"`
	ADRESBILGISI           string `protobuf:"bytes,7,opt,name=aDRESBILGISI,proto3" json:"aDRESBILGISI,omitempty"`
	TELEFONNUMARASI        string `protobuf:"bytes,8,opt,name=tELEFONNUMARASI,proto3" json:"tELEFONNUMARASI,omitempty"`
	HASTATIPI              string `protobuf:"bytes,9,opt,name=hASTATIPI,proto3" json:"hASTATIPI,omitempty"`
	MUAYENEBASLANGICTARIHI string `protobuf:"bytes,10,opt,name=mUAYENEBASLANGICTARIHI,proto3" json:"mUAYENEBASLANGICTARIHI,omitempty"`
	MUAYENEBITISTARIHI     string `protobuf:"bytes,11,opt,name=mUAYENEBITISTARIHI,proto3" json:"mUAYENEBITISTARIHI,omitempty"`
	TANITURU               string `protobuf:"bytes,12,opt,name=tANITURU,proto3" json:"tANITURU,omitempty"`
	ICD10                  string `protobuf:"bytes,13,opt,name=iCD10,proto3" json:"iCD10,omitempty"`
	RECETETARIHI           string `protobuf:"bytes,14,opt,name=rECETETARIHI,proto3" json:"rECETETARIHI,omitempty"`
	RECETENUMARASI         string `protobuf:"bytes,15,opt,name=rECETENUMARASI,proto3" json:"rECETENUMARASI,omitempty"`
	RECETETURU             string `protobuf:"bytes,16,opt,name=rECETETURU,proto3" json:"rECETETURU,omitempty"`
	HEKIMKIMLIKNUMARASI    string `protobuf:"bytes,17,opt,name=hEKIMKIMLIKNUMARASI,proto3" json:"hEKIMKIMLIKNUMARASI,omitempty"`
	ILACBARKODU            string `protobuf:"bytes,18,opt,name=iLACBARKODU,proto3" json:"iLACBARKODU,omitempty"`
	ILACADI                string `protobuf:"bytes,19,opt,name=iLACADI,proto3" json:"iLACADI,omitempty"`
	KUTUADETI              string `protobuf:"bytes,20,opt,name=kUTUADETI,proto3" json:"kUTUADETI,omitempty"`
	ILACKULLANIMSEKLI      string `protobuf:"bytes,21,opt,name=iLACKULLANIMSEKLI,proto3" json:"iLACKULLANIMSEKLI,omitempty"`
	ILACKULLANIMSAYISI     string `protobuf:"bytes,22,opt,name=iLACKULLANIMSAYISI,proto3" json:"iLACKULLANIMSAYISI,omitempty"`
	ILACKULLANIMDOZU       string `protobuf:"bytes,23,opt,name=iLACKULLANIMDOZU,proto3" json:"iLACKULLANIMDOZU,omitempty"`
	ILACKULLANIMPERIYODU   string `protobuf:"bytes,24,opt,name=iLACKULLANIMPERIYODU,proto3" json:"iLACKULLANIMPERIYODU,omitempty"`
}

func (m *MsgCreatePost) Reset()         { *m = MsgCreatePost{} }
func (m *MsgCreatePost) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePost) ProtoMessage()    {}
func (*MsgCreatePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_432e63113d1d48f5, []int{0}
}
func (m *MsgCreatePost) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePost.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePost.Merge(m, src)
}
func (m *MsgCreatePost) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePost) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePost.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePost proto.InternalMessageInfo

func (m *MsgCreatePost) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreatePost) GetSYSTakipNo() string {
	if m != nil {
		return m.SYSTakipNo
	}
	return ""
}

func (m *MsgCreatePost) GetAD() string {
	if m != nil {
		return m.AD
	}
	return ""
}

func (m *MsgCreatePost) GetSOYAD() string {
	if m != nil {
		return m.SOYAD
	}
	return ""
}

func (m *MsgCreatePost) GetDOGUMTARIHI() string {
	if m != nil {
		return m.DOGUMTARIHI
	}
	return ""
}

func (m *MsgCreatePost) GetCINSIYET() string {
	if m != nil {
		return m.CINSIYET
	}
	return ""
}

func (m *MsgCreatePost) GetADRESBILGISI() string {
	if m != nil {
		return m.ADRESBILGISI
	}
	return ""
}

func (m *MsgCreatePost) GetTELEFONNUMARASI() string {
	if m != nil {
		return m.TELEFONNUMARASI
	}
	return ""
}

func (m *MsgCreatePost) GetHASTATIPI() string {
	if m != nil {
		return m.HASTATIPI
	}
	return ""
}

func (m *MsgCreatePost) GetMUAYENEBASLANGICTARIHI() string {
	if m != nil {
		return m.MUAYENEBASLANGICTARIHI
	}
	return ""
}

func (m *MsgCreatePost) GetMUAYENEBITISTARIHI() string {
	if m != nil {
		return m.MUAYENEBITISTARIHI
	}
	return ""
}

func (m *MsgCreatePost) GetTANITURU() string {
	if m != nil {
		return m.TANITURU
	}
	return ""
}

func (m *MsgCreatePost) GetICD10() string {
	if m != nil {
		return m.ICD10
	}
	return ""
}

func (m *MsgCreatePost) GetRECETETARIHI() string {
	if m != nil {
		return m.RECETETARIHI
	}
	return ""
}

func (m *MsgCreatePost) GetRECETENUMARASI() string {
	if m != nil {
		return m.RECETENUMARASI
	}
	return ""
}

func (m *MsgCreatePost) GetRECETETURU() string {
	if m != nil {
		return m.RECETETURU
	}
	return ""
}

func (m *MsgCreatePost) GetHEKIMKIMLIKNUMARASI() string {
	if m != nil {
		return m.HEKIMKIMLIKNUMARASI
	}
	return ""
}

func (m *MsgCreatePost) GetILACBARKODU() string {
	if m != nil {
		return m.ILACBARKODU
	}
	return ""
}

func (m *MsgCreatePost) GetILACADI() string {
	if m != nil {
		return m.ILACADI
	}
	return ""
}

func (m *MsgCreatePost) GetKUTUADETI() string {
	if m != nil {
		return m.KUTUADETI
	}
	return ""
}

func (m *MsgCreatePost) GetILACKULLANIMSEKLI() string {
	if m != nil {
		return m.ILACKULLANIMSEKLI
	}
	return ""
}

func (m *MsgCreatePost) GetILACKULLANIMSAYISI() string {
	if m != nil {
		return m.ILACKULLANIMSAYISI
	}
	return ""
}

func (m *MsgCreatePost) GetILACKULLANIMDOZU() string {
	if m != nil {
		return m.ILACKULLANIMDOZU
	}
	return ""
}

func (m *MsgCreatePost) GetILACKULLANIMPERIYODU() string {
	if m != nil {
		return m.ILACKULLANIMPERIYODU
	}
	return ""
}

type MsgCreatePostResponse struct {
}

func (m *MsgCreatePostResponse) Reset()         { *m = MsgCreatePostResponse{} }
func (m *MsgCreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePostResponse) ProtoMessage()    {}
func (*MsgCreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_432e63113d1d48f5, []int{1}
}
func (m *MsgCreatePostResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePostResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePostResponse.Merge(m, src)
}
func (m *MsgCreatePostResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePostResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreatePost)(nil), "hichain.hichain.MsgCreatePost")
	proto.RegisterType((*MsgCreatePostResponse)(nil), "hichain.hichain.MsgCreatePostResponse")
}

func init() { proto.RegisterFile("hichain/hichain/tx.proto", fileDescriptor_432e63113d1d48f5) }

var fileDescriptor_432e63113d1d48f5 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcd, 0x6e, 0xda, 0x40,
	0x14, 0x85, 0x81, 0x34, 0x24, 0xdc, 0x24, 0x90, 0x4c, 0x48, 0x18, 0x45, 0x95, 0x15, 0xb1, 0x88,
	0xa2, 0xaa, 0xa2, 0x49, 0x2a, 0x75, 0x3f, 0xe0, 0x29, 0xbd, 0xf2, 0x0f, 0xc8, 0x1e, 0x2f, 0x9c,
	0xae, 0x5c, 0x8a, 0x02, 0x8a, 0x1a, 0x23, 0xec, 0x45, 0xfa, 0x16, 0x7d, 0xac, 0x2e, 0xb3, 0xec,
	0xb2, 0x82, 0x55, 0xdf, 0xa2, 0x9a, 0xb1, 0x0d, 0xe6, 0xa7, 0x5d, 0x59, 0xe7, 0x3b, 0xe7, 0x0e,
	0xcc, 0xbd, 0x33, 0x03, 0x74, 0x34, 0x1e, 0x8c, 0x82, 0xf1, 0xd3, 0xbb, 0xec, 0x1b, 0x3f, 0xb7,
	0x26, 0xd3, 0x30, 0x0e, 0x49, 0x2d, 0x25, 0xad, 0xf4, 0xdb, 0xfc, 0x53, 0x86, 0x23, 0x2b, 0x7a,
	0xe8, 0x4c, 0x87, 0x41, 0x3c, 0xec, 0x87, 0x51, 0x4c, 0x28, 0xec, 0x0d, 0xa4, 0x0a, 0xa7, 0xb4,
	0x78, 0x59, 0xbc, 0xae, 0x38, 0x99, 0x24, 0x1a, 0x40, 0xe4, 0xbb, 0x22, 0x78, 0x1c, 0x4f, 0xec,
	0x90, 0x96, 0x94, 0x99, 0x23, 0xa4, 0x0a, 0xa5, 0x40, 0xa7, 0x3b, 0x8a, 0x97, 0x02, 0x9d, 0xd4,
	0x61, 0x37, 0xea, 0xf9, 0x4c, 0xa7, 0xaf, 0x14, 0x4a, 0x04, 0xb9, 0x84, 0x83, 0xaf, 0xbd, 0xae,
	0x67, 0x09, 0xe6, 0xe0, 0x27, 0xa4, 0xbb, 0xca, 0xcb, 0x23, 0x72, 0x01, 0xfb, 0x03, 0xb4, 0x5d,
	0xf4, 0xb9, 0xa0, 0x65, 0x65, 0x2f, 0x34, 0x69, 0xc2, 0x61, 0xa0, 0x3b, 0xdc, 0x6d, 0xa3, 0xd9,
	0x45, 0x17, 0xe9, 0x9e, 0xf2, 0x57, 0x18, 0xb9, 0x86, 0x5a, 0xcc, 0x4d, 0xfe, 0xb1, 0x67, 0xdb,
	0x9e, 0xc5, 0x1c, 0xe6, 0x22, 0xdd, 0x57, 0xb1, 0x75, 0x4c, 0x5e, 0x43, 0x65, 0xc4, 0x5c, 0xc1,
	0x04, 0xf6, 0x91, 0x56, 0x54, 0x66, 0x09, 0xc8, 0x07, 0x38, 0xff, 0xe6, 0x31, 0x9f, 0xdb, 0xbc,
	0xcd, 0x5c, 0x93, 0xd9, 0x5d, 0xec, 0xa4, 0x7f, 0x1a, 0x54, 0xf4, 0x1f, 0x2e, 0x69, 0x01, 0xc9,
	0x1c, 0x14, 0xe8, 0xa6, 0x35, 0x07, 0xaa, 0x66, 0x8b, 0x23, 0xf7, 0x1b, 0x33, 0x1b, 0x85, 0xe7,
	0x78, 0xf4, 0x30, 0xd9, 0x6f, 0xa6, 0x65, 0x0f, 0xc7, 0x1d, 0xfd, 0xf6, 0x86, 0x1e, 0x25, 0x3d,
	0x54, 0x42, 0x76, 0x61, 0xca, 0x3b, 0x5c, 0xf0, 0x74, 0xed, 0x6a, 0xd2, 0x85, 0x3c, 0x23, 0x57,
	0x50, 0x4d, 0xf4, 0xa2, 0x09, 0x35, 0x95, 0x5a, 0xa3, 0x72, 0xaa, 0x69, 0x9d, 0xfc, 0xfd, 0xe3,
	0x64, 0xaa, 0x4b, 0x42, 0x6e, 0xe0, 0x74, 0xc4, 0x0d, 0xb4, 0x0c, 0xb4, 0x4c, 0x34, 0x16, 0x8b,
	0x9d, 0xa8, 0xe0, 0x36, 0x4b, 0x4e, 0x78, 0x6c, 0xb2, 0x4e, 0x9b, 0x39, 0x46, 0x4f, 0xf7, 0x28,
	0x49, 0x26, 0x9c, 0x43, 0xf2, 0x8c, 0x49, 0xc9, 0x74, 0xa4, 0xa7, 0xc9, 0x19, 0x4b, 0xa5, 0x9c,
	0xc8, 0xa3, 0x27, 0x3c, 0xa6, 0x73, 0x81, 0xb4, 0x9e, 0x4c, 0x64, 0x01, 0xc8, 0x5b, 0x38, 0x91,
	0x41, 0xc3, 0x33, 0x4d, 0x66, 0xa3, 0xe5, 0x72, 0xc3, 0x44, 0x7a, 0xa6, 0x52, 0x9b, 0x86, 0x9c,
	0xc3, 0x0a, 0x64, 0xbe, 0x3c, 0x31, 0xe7, 0xc9, 0x1c, 0x36, 0x1d, 0xf2, 0x06, 0x8e, 0xf3, 0x54,
	0xef, 0xdd, 0x7b, 0xb4, 0xa1, 0xd2, 0x1b, 0x9c, 0xdc, 0x41, 0x3d, 0xcf, 0xfa, 0xdc, 0x41, 0x5f,
	0x6e, 0x96, 0xaa, 0xfc, 0x56, 0xaf, 0xd9, 0x80, 0xb3, 0x95, 0xab, 0xe6, 0x0c, 0xa3, 0x49, 0xf8,
	0x14, 0x0d, 0xef, 0x3e, 0xc3, 0x8e, 0x15, 0x3d, 0x10, 0x01, 0x90, 0xbb, 0x87, 0x5a, 0x6b, 0xed,
	0xae, 0xb6, 0x56, 0x8a, 0x2f, 0xae, 0xfe, 0xef, 0x67, 0x8b, 0xb7, 0x6f, 0x7f, 0xce, 0xb4, 0xe2,
	0xcb, 0x4c, 0x2b, 0xfe, 0x9e, 0x69, 0xc5, 0x1f, 0x73, 0xad, 0xf0, 0x32, 0xd7, 0x0a, 0xbf, 0xe6,
	0x5a, 0xe1, 0xbe, 0x91, 0x3d, 0x0f, 0xcf, 0xcb, 0x87, 0xe2, 0xfb, 0x64, 0x18, 0x7d, 0x29, 0xab,
	0xc7, 0xe2, 0xfd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x10, 0x70, 0xa7, 0x48, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreatePost(ctx context.Context, in *MsgCreatePost, opts ...grpc.CallOption) (*MsgCreatePostResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePost(ctx context.Context, in *MsgCreatePost, opts ...grpc.CallOption) (*MsgCreatePostResponse, error) {
	out := new(MsgCreatePostResponse)
	err := c.cc.Invoke(ctx, "/hichain.hichain.Msg/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreatePost(context.Context, *MsgCreatePost) (*MsgCreatePostResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreatePost(ctx context.Context, req *MsgCreatePost) (*MsgCreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hichain.hichain.Msg/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePost(ctx, req.(*MsgCreatePost))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hichain.hichain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _Msg_CreatePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hichain/hichain/tx.proto",
}

func (m *MsgCreatePost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePost) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePost) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ILACKULLANIMPERIYODU) > 0 {
		i -= len(m.ILACKULLANIMPERIYODU)
		copy(dAtA[i:], m.ILACKULLANIMPERIYODU)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ILACKULLANIMPERIYODU)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if len(m.ILACKULLANIMDOZU) > 0 {
		i -= len(m.ILACKULLANIMDOZU)
		copy(dAtA[i:], m.ILACKULLANIMDOZU)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ILACKULLANIMDOZU)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if len(m.ILACKULLANIMSAYISI) > 0 {
		i -= len(m.ILACKULLANIMSAYISI)
		copy(dAtA[i:], m.ILACKULLANIMSAYISI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ILACKULLANIMSAYISI)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb2
	}
	if len(m.ILACKULLANIMSEKLI) > 0 {
		i -= len(m.ILACKULLANIMSEKLI)
		copy(dAtA[i:], m.ILACKULLANIMSEKLI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ILACKULLANIMSEKLI)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if len(m.KUTUADETI) > 0 {
		i -= len(m.KUTUADETI)
		copy(dAtA[i:], m.KUTUADETI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.KUTUADETI)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if len(m.ILACADI) > 0 {
		i -= len(m.ILACADI)
		copy(dAtA[i:], m.ILACADI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ILACADI)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if len(m.ILACBARKODU) > 0 {
		i -= len(m.ILACBARKODU)
		copy(dAtA[i:], m.ILACBARKODU)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ILACBARKODU)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.HEKIMKIMLIKNUMARASI) > 0 {
		i -= len(m.HEKIMKIMLIKNUMARASI)
		copy(dAtA[i:], m.HEKIMKIMLIKNUMARASI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.HEKIMKIMLIKNUMARASI)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.RECETETURU) > 0 {
		i -= len(m.RECETETURU)
		copy(dAtA[i:], m.RECETETURU)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RECETETURU)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.RECETENUMARASI) > 0 {
		i -= len(m.RECETENUMARASI)
		copy(dAtA[i:], m.RECETENUMARASI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RECETENUMARASI)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.RECETETARIHI) > 0 {
		i -= len(m.RECETETARIHI)
		copy(dAtA[i:], m.RECETETARIHI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RECETETARIHI)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.ICD10) > 0 {
		i -= len(m.ICD10)
		copy(dAtA[i:], m.ICD10)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ICD10)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.TANITURU) > 0 {
		i -= len(m.TANITURU)
		copy(dAtA[i:], m.TANITURU)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TANITURU)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.MUAYENEBITISTARIHI) > 0 {
		i -= len(m.MUAYENEBITISTARIHI)
		copy(dAtA[i:], m.MUAYENEBITISTARIHI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MUAYENEBITISTARIHI)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.MUAYENEBASLANGICTARIHI) > 0 {
		i -= len(m.MUAYENEBASLANGICTARIHI)
		copy(dAtA[i:], m.MUAYENEBASLANGICTARIHI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MUAYENEBASLANGICTARIHI)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.HASTATIPI) > 0 {
		i -= len(m.HASTATIPI)
		copy(dAtA[i:], m.HASTATIPI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.HASTATIPI)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.TELEFONNUMARASI) > 0 {
		i -= len(m.TELEFONNUMARASI)
		copy(dAtA[i:], m.TELEFONNUMARASI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TELEFONNUMARASI)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ADRESBILGISI) > 0 {
		i -= len(m.ADRESBILGISI)
		copy(dAtA[i:], m.ADRESBILGISI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ADRESBILGISI)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CINSIYET) > 0 {
		i -= len(m.CINSIYET)
		copy(dAtA[i:], m.CINSIYET)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CINSIYET)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DOGUMTARIHI) > 0 {
		i -= len(m.DOGUMTARIHI)
		copy(dAtA[i:], m.DOGUMTARIHI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DOGUMTARIHI)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SOYAD) > 0 {
		i -= len(m.SOYAD)
		copy(dAtA[i:], m.SOYAD)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SOYAD)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AD) > 0 {
		i -= len(m.AD)
		copy(dAtA[i:], m.AD)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AD)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SYSTakipNo) > 0 {
		i -= len(m.SYSTakipNo)
		copy(dAtA[i:], m.SYSTakipNo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SYSTakipNo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePostResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePostResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePostResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreatePost) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SYSTakipNo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AD)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SOYAD)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DOGUMTARIHI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CINSIYET)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ADRESBILGISI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TELEFONNUMARASI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.HASTATIPI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MUAYENEBASLANGICTARIHI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MUAYENEBITISTARIHI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TANITURU)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ICD10)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RECETETARIHI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RECETENUMARASI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RECETETURU)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.HEKIMKIMLIKNUMARASI)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.ILACBARKODU)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.ILACADI)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.KUTUADETI)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.ILACKULLANIMSEKLI)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.ILACKULLANIMSAYISI)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.ILACKULLANIMDOZU)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	l = len(m.ILACKULLANIMPERIYODU)
	if l > 0 {
		n += 2 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePostResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreatePost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SYSTakipNo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SYSTakipNo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AD", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AD = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SOYAD", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SOYAD = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DOGUMTARIHI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DOGUMTARIHI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CINSIYET", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CINSIYET = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ADRESBILGISI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ADRESBILGISI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TELEFONNUMARASI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TELEFONNUMARASI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HASTATIPI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HASTATIPI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MUAYENEBASLANGICTARIHI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MUAYENEBASLANGICTARIHI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MUAYENEBITISTARIHI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MUAYENEBITISTARIHI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TANITURU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TANITURU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ICD10", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ICD10 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RECETETARIHI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RECETETARIHI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RECETENUMARASI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RECETENUMARASI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RECETETURU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RECETETURU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HEKIMKIMLIKNUMARASI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HEKIMKIMLIKNUMARASI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ILACBARKODU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ILACBARKODU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ILACADI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ILACADI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KUTUADETI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KUTUADETI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ILACKULLANIMSEKLI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ILACKULLANIMSEKLI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ILACKULLANIMSAYISI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ILACKULLANIMSAYISI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ILACKULLANIMDOZU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ILACKULLANIMDOZU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ILACKULLANIMPERIYODU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ILACKULLANIMPERIYODU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePostResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePostResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePostResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
